name: Monitoramento Atibainha

on:
  schedule:
    - cron: "*/15 * * * *"   # Executa automaticamente a cada 15 minutos
  workflow_dispatch:        # Permite que você execute manualmente clicando num botão

jobs:
  monitoramento:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install requests

      - name: Executar script de monitoramento
        env:
          # É aqui que o GitHub "conecta" os segredos ao seu código Python
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitoramento.py
