name: Monitoramento de Chuva Atibainha

on:
  schedule:
    # O cron abaixo roda a cada 1 hora (no minuto 0)
    # Se quiser mudar para cada 15 min, use: '*/15 * * * *'
    - cron: '0 * * * *'
  workflow_dispatch: # Permite rodar manualmente na aba Actions

jobs:
  verificar_clima:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas necessárias
        run: pip install requests

      - name: Executar Script de Monitoramento
        env:
          # Liga os Secrets do GitHub às variáveis do script
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python monitoramento.py
