name: Monitoramento de Chuva Atibainha

on:
  schedule:
    # O cron abaixo roda a cada 1 hora (no minuto 0)
    # 0 * * * * significa: minuto 0, de todas as horas, todos os dias.
    - cron: '0 * * * *'
  workflow_dispatch: # Isso permite que você rode o script manualmente para testar

jobs:
  verificar_clima:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas necessárias
        run: pip install requests

      - name: Executar Script de Monitoramento
        env:
          # Aqui o GitHub liga os Secrets que você criou às variáveis do Python
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python monitoramento.py
